on:
  push:
    tags:
      # Example: 8.4.1
      - 8\.\d+\.\d+
jobs:
  release_script:
    if: ! contains($GITHUB_REF_NAME, "+")
    runs-on: ubuntu-latest
    name: Build release script
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Build
        working-directory: ./release-notes-fetcher
        run: go build

      - name: Generate token for Camunda GitHub org
        id: generate-camunda-github-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Generate token for Camunda Cloud GitHub org
        id: generate-camunda-cloud-github-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          repository: camunda-cloud/identity

      - name: Run release notes script
        working-directory: ./release-notes-fetcher
        run: set -o pipefail; ./release-notes-fetcher | tee release_notes.txt
        env:
          GITHUB_CAMUNDA_ACCESS_TOKEN: ${{ steps.generate-camunda-github-token.outputs.token }}
          GITHUB_CAMUNDA_CLOUD_ACCESS_TOKEN: ${{ steps.generate-camunda-cloud-github-token.outputs.token }}

      - name: Login to gh repo
        working-directory: ./release-notes-fetcher
        run: echo ${{ steps.generate-camunda-github-token.outputs.token }} | gh auth login --with-token

      - name: Edit release notes with output from script
        working-directory: ./release-notes-fetcher
        run: gh release edit --notes-file release_notes.txt -R camunda/camunda-platform $GITHUB_REF_NAME

      - name: Create temporary directory for asset download/upload
        working-directory: ./release-notes-fetcher
        run: mkdir -p tmp

      # Tasklist binaries are uploaded to zeebes repo
      - name: Download Zeebe resources
        working-directory: ./release-notes-fetcher/tmp
        run: >
          gh release
          download "$GITHUB_REF_NAME"
          -R camunda/zeebe
          -p "zbctl"
          -p "zbctl.sha1sum"
          -p "zbctl.exe"
          -p "zbctl.exe.sha1sum"
          -p "zbctl.darwin"
          -p "zbctl.darwin.sha1sum"
          -p "camunda-zeebe-$GITHUB_REF_NAME.tar.gz"
          -p "camunda-zeebe-$GITHUB_REF_NAME.tar.gz.sha1sum"
          -p "camunda-zeebe-$GITHUB_REF_NAME.zip"
          -p "camunda-zeebe-$GITHUB_REF_NAME.zip.sha1sum"
          -p "camunda-tasklist-$GITHUB_REF_NAME.zip"
          -p "camunda-tasklist-$GITHUB_REF_NAME.zip.sha1sum"
          -p "camunda-tasklist-$GITHUB_REF_NAME.tar.gz"
          -p "camunda-tasklist-$GITHUB_REF_NAME.tar.gz.sha1sum"

      - name: Download Operate resources from monorepo
        if: ${{ startsWith(env.GITHUB_REF_NAME, '8.5') }}
        working-directory: ./release-notes-fetcher/tmp
        run: >
          gh release
          download "operate-$GITHUB_REF_NAME"
          -R camunda/zeebe
          -p "camunda-operate-$GITHUB_REF_NAME.zip"
          -p "camunda-operate-$GITHUB_REF_NAME.zip.sha1sum"
          -p "camunda-operate-$GITHUB_REF_NAME.tar.gz"
          -p "camunda-operate-$GITHUB_REF_NAME.tar.gz.sha1sum"

      - name: Download Operate resources
        if: ${{ !startsWith(env.GITHUB_REF_NAME, '8.5') }}
        working-directory: ./release-notes-fetcher/tmp
        run: >
          gh release
          download "$GITHUB_REF_NAME"
          -R camunda/operate
          -p "camunda-operate-$GITHUB_REF_NAME.zip"
          -p "camunda-operate-$GITHUB_REF_NAME.zip.sha1sum"
          -p "camunda-operate-$GITHUB_REF_NAME.tar.gz"
          -p "camunda-operate-$GITHUB_REF_NAME.tar.gz.sha1sum"

      - name: Login to Camunda Cloud
        working-directory: ./release-notes-fetcher
        run: echo ${{ steps.generate-camunda-cloud-github-token.outputs.token }} | gh auth login --with-token

      - name: Download Identity resources
        working-directory: ./release-notes-fetcher/tmp
        run: >
          gh release
          download "$GITHUB_REF_NAME"
          -R camunda-cloud/identity
          -p "camunda-identity-$GITHUB_REF_NAME.tar.gz"
          -p "camunda-identity-$GITHUB_REF_NAME.tar.gz.sha1sum"
          -p "camunda-identity-$GITHUB_REF_NAME.zip"
          -p "camunda-identity-$GITHUB_REF_NAME.zip.sha1sum"

      - name: Login back to Camunda
        working-directory: ./release-notes-fetcher
        run: echo ${{ steps.generate-camunda-github-token.outputs.token }} | gh auth login --with-token

      - name: Upload resources
        working-directory: ./release-notes-fetcher/tmp
        run: gh release -R camunda/camunda-platform upload "$GITHUB_REF_NAME" *
